### ISSUE TITLE
HybirdNet ROI_CUBE_SIZE issue

### ISSUE THREAD

**Issue by vigji** [JARVIS-MoCap/JARVIS-HybridNet#2]
I tried to start training a network with some data.

I specify those parameters:

```
"HYBRIDNET":{
"BATCH_SIZE":1
"MAX_LEARNING_RATE":0.003
"NUM_EPOCHS":30
"CHECKPOINT_SAVE_INTERVAL":10
"NUM_CAMERAS":3
"ROI_CUBE_SIZE":136
"GRID_SPACING":2
}
```

As far as I understand, `ROI_CUBE_SIZE` has to be divisible by 4 * GRID_SPACING (which seems to be the case to me here). However, by launching the training with those parameters I get the following error:

`HybirdNet ROI_CUBE_SIZE has to be divisible by 4 * GRID_SPACING!`

**Comment by JARVIS-MoCap** [comment]
Hi again, thanks alot for reporting all those bugs! And sorry that you seem to stumble across them all.

Apperently I changed the error message at some point, but never the actual divisibility check from 8 down to 4. I just pushed the working version of that file. 
If you don't want to pull a new version of the code you can also just slightly increase your ROI_CUBE_SIZE to 144. Since 144 is divisible by 8 it will pass the broken check.

**Comment by vigji** [comment]
No problems at all, I know how hard are the first days in the wild! :)
Will try tomorrow the fix. Thank you very much!
